
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }



#[language-server.rust-analyzer.config.check]
#command = "clippy"

#[[language]]
#name = "rust"
#auto-format = true



#Download lldb on Arch
#[language.debugger]
#name = "lldb-vscode"
#transport = "stdio"
#command = "lldb-vscode"

#To make Rust Debugger work, make the file!
#[[language.debugger.templates]]
#name = "binary"
#request = "launch"
#completion = [ { name = "binary", completion = "filename" } ]
#args = { program = "{0}", initCommands = [ "command script import /usr/local/etc/lldb_vscode_rustc_primer.py" ] }
